import { buildOpenApiDocument } from '@/lib/api/openapi';
import { createSchema } from 'zod-openapi';
import { ErrorSchema, ValidationErrorSchema, UnauthorizedSchema, NotFoundSchema } from '@/lib/api/errors';
import { UserProfileResponseSchema } from '@/lib/api/models/user';

import { healthPath } from '@/app/api/health/openapi';
import { contactPath } from '@/app/api/contact/openapi';
import { chatPath } from '@/app/api/chat/openapi';
import { webauthnLoginOptionsPath } from '@/app/api/auth/webauthn/login-options/openapi';
import { webauthnLoginVerifyPath } from '@/app/api/auth/webauthn/login-verify/openapi';
import { webauthnRegisterOptionsPath } from '@/app/api/auth/webauthn/register-options/openapi';
import { webauthnRegisterVerifyPath } from '@/app/api/auth/webauthn/register-verify/openapi';
import { logoutPath } from '@/app/api/auth/logout/openapi';
import { loginPath } from '@/app/api/auth/login/openapi';
import { refreshPath } from '@/app/api/auth/refresh/openapi';
import { testCookiesPath } from '@/app/api/auth/test-cookies/openapi';
import { googleStartPath } from '@/app/api/auth/google/openapi';
import { googleCallbackPath } from '@/app/api/auth/google/callback/openapi';
import { mobilePasswordPath } from '@/app/api/mobile/v1/auth/password/openapi';
import { mobileMfaEmailPath } from '@/app/api/mobile/v1/auth/mfa/email/openapi';
import { mobileMfaTotpPath } from '@/app/api/mobile/v1/auth/mfa/totp/openapi';
import { mobileMfaWebauthnOptionsPath } from '@/app/api/mobile/v1/auth/mfa/webauthn/options/openapi';
import { mobileMfaWebauthnVerifyPath } from '@/app/api/mobile/v1/auth/mfa/webauthn/verify/openapi';
import { mobilePasskeysPath } from '@/app/api/mobile/v1/auth/passkeys/openapi';
import { mobilePasskeyByIdPath } from '@/app/api/mobile/v1/auth/passkeys/[id]/openapi';
import { mobilePasskeyRegisterOptionsPath } from '@/app/api/mobile/v1/auth/passkeys/register/options/openapi';
import { mobilePasskeyRegisterVerifyPath } from '@/app/api/mobile/v1/auth/passkeys/register/verify/openapi';
import { mobilePasskeyLoginOptionsPath } from '@/app/api/mobile/v1/auth/passkeys/login/options/openapi';
import { mobilePasskeyLoginVerifyPath } from '@/app/api/mobile/v1/auth/passkeys/login/verify/openapi';
import { mobileMePath } from '@/app/api/mobile/v1/auth/me/openapi';
import { mobileRefreshPath } from '@/app/api/mobile/v1/auth/refresh/openapi';
import { mobileGooglePath } from '@/app/api/mobile/v1/auth/google/openapi';
import { mobileLogoutPath } from '@/app/api/mobile/v1/auth/logout/openapi';
import { userGetByIdPath } from '@/app/api/mobile/v1/users/[id]/openapi';
import { jwksPath } from '@/app/api/mobile/v1/.well-known/jwks.json/openapi';
import { adminCategoriesPath } from '@/app/api/mobile/v1/admin/categories/openapi';
import { adminCategoryUpdatePath } from '@/app/api/mobile/v1/admin/categories/[id]/openapi';
import { adminProductsPath } from '@/app/api/mobile/v1/admin/products/openapi';
import { adminProductUpdatePath } from '@/app/api/mobile/v1/admin/products/[id]/openapi';
import { adminSessionsRevokePath } from '@/app/api/mobile/v1/admin/sessions/revoke/openapi';
import { adminSectionsPath } from '@/app/api/mobile/v1/admin/sections/openapi';
import { adminSectionUpdatePath } from '@/app/api/mobile/v1/admin/sections/[id]/openapi';

export const EXCLUDED_ROUTES = [
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/admin/sections',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/admin/sections/{id}',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/me',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/refresh',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/password',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/mfa/email',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/mfa/totp',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/mfa/webauthn/options',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/mfa/webauthn/verify',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/passkeys',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/passkeys/{id}',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/passkeys/register/options',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/passkeys/register/verify',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/passkeys/login/options',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/passkeys/login/verify',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate: 'OPTIONS returns CORS headers with no user-facing response body.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/google',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/auth/logout',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/users/{id}',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
  {
    method: 'OPTIONS',
    path: '/api/mobile/v1/.well-known/jwks.json',
    reason: 'CORS preflight handler — automatically generated by mobile middleware',
    category: 'cors-preflight',
    securityVisibility: 'public',
    whyInappropriate:
      'OPTIONS handlers return CORS headers with no body. They are automatically ' +
      'invoked by browsers before cross-origin requests and do not represent user-facing API operations.',
  },
];

function mergePaths(
  ...pathObjects: Array<Record<string, unknown>>
): Record<string, unknown> {
  const merged: Record<string, unknown> = {};
  for (const obj of pathObjects) {
    for (const [key, value] of Object.entries(obj)) {
      if (merged[key]) {
        Object.assign(merged[key], value);
      } else {
        merged[key] = value;
      }
    }
  }
  return merged;
}

export function assembleOpenApiDocument() {
  const doc = buildOpenApiDocument();

  doc.paths = mergePaths(
    healthPath as Record<string, unknown>,
    contactPath as Record<string, unknown>,
    chatPath as Record<string, unknown>,
    webauthnLoginOptionsPath as Record<string, unknown>,
    webauthnLoginVerifyPath as Record<string, unknown>,
    webauthnRegisterOptionsPath as Record<string, unknown>,
    webauthnRegisterVerifyPath as Record<string, unknown>,
    logoutPath as Record<string, unknown>,
    loginPath as Record<string, unknown>,
    refreshPath as Record<string, unknown>,
    testCookiesPath as Record<string, unknown>,
    googleStartPath as Record<string, unknown>,
    googleCallbackPath as Record<string, unknown>,
    mobilePasswordPath as Record<string, unknown>,
    mobileMfaEmailPath as Record<string, unknown>,
    mobileMfaTotpPath as Record<string, unknown>,
    mobileMfaWebauthnOptionsPath as Record<string, unknown>,
    mobileMfaWebauthnVerifyPath as Record<string, unknown>,
    mobilePasskeysPath as Record<string, unknown>,
    mobilePasskeyByIdPath as Record<string, unknown>,
    mobilePasskeyRegisterOptionsPath as Record<string, unknown>,
    mobilePasskeyRegisterVerifyPath as Record<string, unknown>,
    mobilePasskeyLoginOptionsPath as Record<string, unknown>,
    mobilePasskeyLoginVerifyPath as Record<string, unknown>,
    mobileMePath as Record<string, unknown>,
    mobileRefreshPath as Record<string, unknown>,
    mobileGooglePath as Record<string, unknown>,
    mobileLogoutPath as Record<string, unknown>,
    userGetByIdPath as Record<string, unknown>,
    jwksPath as Record<string, unknown>,
    adminCategoriesPath as Record<string, unknown>,
    adminCategoryUpdatePath as Record<string, unknown>,
    adminProductsPath as Record<string, unknown>,
    adminProductUpdatePath as Record<string, unknown>,
    adminSessionsRevokePath as Record<string, unknown>,
    adminSectionsPath as Record<string, unknown>,
    adminSectionUpdatePath as Record<string, unknown>,
  ) as typeof doc.paths;

  if (!doc.components) doc.components = {};
  if (!doc.components.schemas) doc.components.schemas = {};

  const componentSchemas = [
    ErrorSchema,
    ValidationErrorSchema,
    UnauthorizedSchema,
    NotFoundSchema,
    UserProfileResponseSchema,
  ];

  for (const schema of componentSchemas) {
    const result = createSchema(schema);
    for (const [name, schemaDef] of Object.entries(result.components)) {
      doc.components.schemas[name] = schemaDef;
    }
  }

  return doc;
}
