const error = { description: 'Error', content: { 'application/json': { schema: { type: 'object', properties: { error: { type: 'string' } } } } } };
const catalog = { type: 'object', required: ['_id', 'title', 'slug', 'status', 'pages'], properties: { _id: { type: 'string' }, categoryId: { type: ['string', 'null'] }, productId: { type: ['string', 'null'] }, title: { type: 'string' }, slug: { type: 'string' }, description: { type: 'string' }, status: { type: 'string', enum: ['draft', 'published'] }, pages: { type: 'array', items: { type: 'object' } }, asset: { type: 'object' }, markdown: { type: 'string' }, sceneVersion: { type: ['integer', 'null'] }, scene: { type: ['object', 'null'] }, processingError: { type: ['string', 'null'] }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } };
const security = [{ bearerAuth: [] }];
const responses = { '400': error, '401': error, '403': error, '500': error };

export const adminCatalogsPaths = {
  '/api/mobile/v1/admin/catalogs': {
    get: { tags: ['Mobile Admin'], summary: 'List catalog documents', operationId: 'listCatalogsMobile', security, parameters: [{ in: 'query', name: 'categoryId', schema: { type: 'string' } }, { in: 'query', name: 'productId', schema: { type: 'string' } }], responses: { '200': { description: 'Catalogs', content: { 'application/json': { schema: { type: 'object', properties: { success: { type: 'boolean' }, catalogs: { type: 'array', items: catalog } } } } } }, ...responses } },
    post: { tags: ['Mobile Admin'], summary: 'Initialize or finalize catalog creation', operationId: 'createCatalogMobile', security, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['operation'], properties: { operation: { type: 'string', enum: ['initialize', 'finalize'] }, catalog: { type: 'object' }, publicId: { type: 'string' } } } } } }, responses: { '201': { description: 'Created' }, '200': { description: 'Upload initialized' }, ...responses } },
  },
  '/api/mobile/v1/admin/catalogs/{id}': {
    get: { tags: ['Mobile Admin'], summary: 'Get catalog', operationId: 'getCatalogMobile', security, parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Catalog', content: { 'application/json': { schema: catalog } } }, '404': error, ...responses } },
    patch: { tags: ['Mobile Admin'], summary: 'Update catalog metadata', operationId: 'updateCatalogMobile', security, parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { title: { type: 'string' }, description: { type: 'string' } } } } } }, responses: { '200': { description: 'Updated' }, ...responses } },
    delete: { tags: ['Mobile Admin'], summary: 'Delete catalog', operationId: 'deleteCatalogMobile', security, parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], responses: { '200': { description: 'Deleted' }, ...responses } },
  },
  '/api/mobile/v1/admin/catalogs/{id}/associations': { patch: { tags: ['Mobile Admin'], summary: 'Update catalog associations', operationId: 'updateCatalogAssociationsMobile', security, parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { categoryId: { type: ['string', 'null'] }, productId: { type: ['string', 'null'] } } } } } }, responses: { '200': { description: 'Updated' }, ...responses } } },
  '/api/mobile/v1/admin/catalogs/{id}/publication': { post: { tags: ['Mobile Admin'], summary: 'Publish or unpublish catalog', operationId: 'setCatalogPublicationMobile', security, parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['published'], properties: { published: { type: 'boolean' } } } } } }, responses: { '200': { description: 'Updated' }, ...responses } } },
  '/api/mobile/v1/admin/catalogs/{id}/replacement': { post: { tags: ['Mobile Admin'], summary: 'Initialize or finalize PDF replacement', operationId: 'replaceCatalogPdfMobile', security, parameters: [{ in: 'path', name: 'id', required: true, schema: { type: 'string' } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['operation'], properties: { operation: { type: 'string', enum: ['initialize', 'finalize'] }, publicId: { type: 'string' } } } } } }, responses: { '200': { description: 'Replacement initialized or completed' }, ...responses } } },
};
