import { randomBytes, createCipheriv, createDecipheriv } from 'node:crypto';

// ─────────────────────────────────────────────────────────────────────────────
// Symmetric Encryption (AES-256-GCM)
//
// Used for encrypting sensitive data at rest (e.g., TOTP seeds).
// We use AES-256-GCM, which provides both confidentiality and authenticity.
//
// Payload Format: "v1:<ivHex>:<authTagHex>:<ciphertextHex>"
// ─────────────────────────────────────────────────────────────────────────────

const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // 96 bits is recommended for GCM
const PREFIX_V1 = 'v1';

/**
 * Encrypts a plaintext string using AES-256-GCM.
 *
 * @param plaintext The string to encrypt.
 * @param hexKey A 32-byte (64-character) hex-encoded encryption key.
 * @returns The versioned ciphertext payload string.
 */
export function encryptSymmetric(plaintext: string, hexKey: string): string {
  if (!hexKey || hexKey.length !== 64) {
    throw new Error('encryptSymmetric requires a 64-character hex key (32 bytes).');
  }

  const keyBuffer = Buffer.from(hexKey, 'hex');
  if (keyBuffer.length !== 32) {
    throw new Error('encryptSymmetric hexKey must be exactly 32 bytes.');
  }

  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGORITHM, keyBuffer, iv);

  let ciphertext = cipher.update(plaintext, 'utf8', 'hex');
  ciphertext += cipher.final('hex');

  const authTag = cipher.getAuthTag().toString('hex');

  return `${PREFIX_V1}:${iv.toString('hex')}:${authTag}:${ciphertext}`;
}

/**
 * Decrypts a versioned payload string using AES-256-GCM.
 *
 * @param payload The payload generated by encryptSymmetric.
 * @param hexKey A 32-byte (64-character) hex-encoded encryption key.
 * @returns The decrypted plaintext string.
 */
export function decryptSymmetric(payload: string, hexKey: string): string {
  if (!hexKey || hexKey.length !== 64) {
    throw new Error('decryptSymmetric requires a 64-character hex key (32 bytes).');
  }

  const keyBuffer = Buffer.from(hexKey, 'hex');
  if (keyBuffer.length !== 32) {
    throw new Error('decryptSymmetric hexKey must be exactly 32 bytes.');
  }

  const parts = payload.split(':');
  if (parts.length !== 4 || parts[0] !== PREFIX_V1) {
    throw new Error('Invalid or unsupported encrypted payload format.');
  }

  const [, ivHex, authTagHex, ciphertextHex] = parts;

  const iv = Buffer.from(ivHex, 'hex');
  const authTag = Buffer.from(authTagHex, 'hex');

  const decipher = createDecipheriv(ALGORITHM, keyBuffer, iv);
  decipher.setAuthTag(authTag);

  try {
    let plaintext = decipher.update(ciphertextHex, 'hex', 'utf8');
    plaintext += decipher.final('utf8');
    return plaintext;
  } catch (err) {
    throw new Error('Decryption failed: incorrect key or corrupted payload.');
  }
}
